[package]
name = "prune"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "prune"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.0"
futures = "0.3.21"
async-recursion = "1.0.0"